### ISSUE TITLE
Add use cases for other basic MVP features

### ISSUE THREAD

**Issue by cellio** [codidact/feature-development#10]
Yeah vague I know. :-)  Comments and their handling, voting, edit, others not covered by other issues.  (I've already started a branch and belatedly realized I should have an issue to track it.)

Work is being done on https://github.com/codidact/feature-development/tree/cellio/mvp-basics.

**Comment by cellio** [comment]
Comments: I reviewed [this forum thread](https://forum.codidact.org/t/comments-discussions-and-requests-for-clarification/984?u=cellio), which was too ambitious and complicated for MVP.  What I kept:

- threaded comments (but not layers and layers of indentation), with expand/collapse for the thread
- threads can be muted by people who are getting notified
- threads can be archived or deleted by moderators (archived means not shown by default but users with appropriate trust level can see them)
- individual comments can be deleted by mods 

I didn't include the idea of the author marking comments as "resolved"; archiving would accomplish the same thing and can be requested in a flag, so let's see if that's good enough.

**Comment by cellio** [comment]
Added edit use cases:
- propose edit
- author reviews edit (author gets notification and vote is binding, so this is different from the general case)
- anybody else reviews while browsing

There are no review queues; you notice a pending edit because you see the post, or you're the author and get notified.  That's what we said in the functional spec.

**Comment by cellio** [comment]
Added (in flags directory) suggest duplicate and vote to close.  I deliberately separated duplicate out from the close idea.  We should think of duplicate suggestions as *getting your answer faster* rather than the more-hostile-sounding "close question" idea.  We'll want to craft the language shown to the OP and public for both dupe and close, and probably not call it "close".  There are two close reasons now, "needs attention" and "off topic". 

Still to do: OP response, in-place review (like for edits, you can interact with the pending action on the question page itself but there's no review queue), reopen.

**Comment by cellio** [comment]
Added use cases for vote-to-close/hold/reopen.  Here's the high-level summary:

- The *first* vote to put on hold adds a notice (special guidance for OP) and notifies OP.
- People who see the question in this state and are TL3 can add votes to hold OR to keep open.  We do not wait for closure; people can essentially dispute close votes from the start.
- If hold votes exceed open votes by the threshold, question is put on hold.
- If open votes equal hold votes, the notice is removed (but kept in the post history).
- An edit from the OP cancels a hold.  Yes on a larger site or one prone to trolls this could be abused, but let's try this first. Presume good intent.
- An edit from anybody with TL3 casts an open vote (and we remind the editor of this).

**Comment by mattjbrent** [comment]
This is great @cellio I think we will need to go through each one and expand on features (ie more details) but this is an amazing start
